print('this is the python code. Python is the king')
print('this is the python code. Python is the king')
print('this is the python code. Python is the king')
print('this is the python code. Python is the king')
print('this is the python code. Python is the king')
print('this is the python code. Python is the king')
print('this is the python print('this is the python code. Python is the king')
