print('this is the python code. Python is the king')
print('this is the python code. Python is the king')
print('this is the python code. Python is the king')
print('this is the python code. Python is the king')
print('this is the python code. Python is the king')
print('this is the python code. Python is the king')
print('this is print('this is the python code. Python is the king')
